{% set name = "eagerpy" %}
{% set version = "0.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 014c02b5a7f7e19f8471885cf8aa469f2e9cf518c88400f20b6b8db83d413106

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - python
    - typing-extensions >=3.7.4.1

test:
  imports:
    - eagerpy
    - eagerpy.tensor

about:
  home: https://eagerpy.jonasrauber.de/
  license: MIT
  license_family: MIT
  license_file: LICENSE # PR here: https://github.com/jonasrauber/eagerpy/pull/7
  summary: EagerPy is a thin wrapper around PyTorch, TensorFlow Eager, JAX and NumPy that unifies their interface and thus allows writing code that works natively across all of them.
  doc_url: https://eagerpy.jonasrauber.de/
  dev_url: https://github.com/jonasrauber/eagerpy

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
